# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pr:
  - none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.2'
  displayName: 'install Node'


- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'build'
    azure_static_web_apps_api_token:  $(private_site_deployment_token)
